name: CI
on:
  push:
    branches:
      - main
    paths:
      - "images/src/**/.devcontainer/Dockerfile"
      - "images/src/**/.devcontainer/.devcontainer.json"
      - "images/src/**/.devcontainer/*/**"
      - "images/src/**/.devcontainer/manifest.json"
      - "!images/src/**/README.md"
      # - "features/src/**"
      # - "!features/src/**/README.md"
      # - "!features/src/**/NOTES.md"
      # - "templates/src/**"
      # - "!templates/src/**/README.md"
      # - "!templates/src/**/NOTES.md"

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - base-ubuntu
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Publish Images
        uses: ./.github/actions/publish-image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          push: true
          image: ${{ matrix.images }}
          registry: ghcr.io
          repository: ${{ github.repository_owner }}/devcontainer-images
          username: ${{ github.repository_owner }}

  # features:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: write
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Publish Features
  #       uses: devcontainers/action@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         publish-features: "true"
  #         base-path-to-features: "./features/src"
  #         oci-registry: ghcr.io
  #         features-namespace: ${{ github.repository_owner }}/devcontainer-features
  #         generate-docs: "false"

  # templates:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: write
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Publish Templates
  #       uses: devcontainers/action@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         publish-templates: "true"
  #         base-path-to-templates: "./templates/src"
  #         oci-registry-for-templates: ghcr.io
  #         templates-namespace: ${{ github.repository_owner }}/devcontainer-templates
  #         generate-docs: "false"